# This is a basic workflow to help you get started with Actions

name: Secret-token-leaks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read
jobs:
  TruffleHog:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@a7fc12240f8ce02df55c8b808755088f3b7eec7d
        with:
          path: ./mas-crackmes/Android/Level1 
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
          
      - name: Checkout code2
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@a7fc12240f8ce02df55c8b808755088f3b7eec7d
        with:
          path: ./mas-crackmes/Android/Level2 
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
          
          
      - name: Checkout code3
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@a7fc12240f8ce02df55c8b808755088f3b7eec7d
        with:
          path: ./mas-crackmes/Android/Level3 
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
          
          
      - name: Checkout code4
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@a7fc12240f8ce02df55c8b808755088f3b7eec7d
        with:
          path: ./mas-crackmes/Android/Level4 
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
          
